use 5.034;
use strict;
use warnings;
use Test::More;
use DBI ();
use JSON::PP ();
use Selecto;
use Selecto::Certification ();

my $url = $ENV{SELECTO_PERL_TEST_POSTGRES_URL};
plan skip_all => 'SELECTO_PERL_TEST_POSTGRES_URL is not configured' unless defined($url) && $url ne '';
plan skip_all => 'DBD::Pg is not installed' unless eval { require DBD::Pg; 1 };

my ($dsn, $username, $password) = Selecto::Certification::_connection_parts($url);
my $dbh = DBI->connect($dsn, $username, $password, {
    RaiseError => 1, PrintError => 0, AutoCommit => 1, pg_enable_utf8 => 1,
});
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_items');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_form_grandchildren');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_form_children');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_graph_children');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_graph_parents');
$dbh->do('CREATE TABLE selecto_perl_test_items (id integer primary key, name text not null)');
$dbh->do(q{INSERT INTO selecto_perl_test_items VALUES (1, 'baseline')});

my $domain = Selecto::Domain->new(
    name => 'Items', table => 'selecto_perl_test_items', fields => { id => 'integer', name => 'string' },
);
my $engine = Selecto::Engine->new(domain => $domain, adapter => Selecto->adapter(postgresql => (dbh => $dbh)));
my $result = $engine->all($engine->query->select('id', 'name')->order_by('id'));
is_deeply($result, { columns => ['id', 'name'], rows => [[1, 'baseline']] }, 'public query API executes through DBD::Pg');

my $first = Selecto::Write::Command->new(
    operation => 'insert', relation => 'selecto_perl_test_items', assignments => { id => 2, name => 'must-roll-back' },
);
my $second = Selecto::Write::Command->new(
    operation => 'update', relation => 'selecto_perl_test_items', assignments => { name => 'never' },
    predicate => Selecto::Expression->eq('id', 999),
);
eval { $engine->execute_batch(Selecto::Write::Batch->new($first, $second)) };
is($@->code, 'cardinality_mismatch', 'live batch reports portable cardinality error');
is($dbh->selectrow_array('SELECT count(*) FROM selecto_perl_test_items'), 1, 'failed live batch rolls back atomically');

$dbh->do('CREATE TABLE selecto_perl_test_graph_parents (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text NOT NULL)');
$dbh->do('CREATE TABLE selecto_perl_test_graph_children (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_id integer NOT NULL REFERENCES selecto_perl_test_graph_parents(id), label text NOT NULL)');
my $graph_domain = Selecto::Domain->parse({
    schema_version => 1,
    name           => 'GraphParents',
    source         => {
        source_table => 'selecto_perl_test_graph_parents',
        primary_key  => 'id',
        fields       => ['id', 'label'],
        columns      => { id => { type => 'integer' }, label => { type => 'string' } },
        associations => {},
    },
    schemas => {}, joins => {},
    writes => {
        operations => { insert => { enabled => JSON::PP::true } },
        fields     => { label  => { insertable => JSON::PP::true } },
        relationships => {
            children => {
                writable    => JSON::PP::true,
                cardinality => 'many',
                allowed_ops => ['insert'],
                ownership   => 'owned',
                foreign_key => 'parent_id',
                table       => 'selecto_perl_test_graph_children',
            },
        },
    },
});
my $graph_engine = Selecto::Engine->new(domain => $graph_domain, adapter => Selecto->adapter(postgresql => (dbh => $dbh)));
my $ungoverned_child = Selecto::Write::Graph->new(nodes => [
    { id => 'parent', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_graph_parents', assignments => { label => 'nope' },
    ) },
    { id => 'child', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_undeclared', assignments => { label => 'child' },
    ), bindings => [{field => 'parent_id', from => 'parent', key => 'id'}] },
]);
eval { $graph_engine->execute_graph($ungoverned_child); 1 };
is($@->code, 'write_relation_mismatch', 'graph child relations must be declared writable relationships');
my $graph = Selecto::Write::Graph->new(nodes => [
    { id => 'parent', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_graph_parents', assignments => {label => 'parent'}, metadata => {returning => ['id']},
    ) },
    { id => 'child', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_graph_children', assignments => {label => 'child'},
    ), bindings => [{field => 'parent_id', from => 'parent', key => 'id'}] },
]);
my $graph_result = $graph_engine->execute_graph($graph);
is($graph_result->root->values->{id}, 1, 'live graph returns the generated root id');
is($dbh->selectrow_array('SELECT parent_id FROM selecto_perl_test_graph_children WHERE label = ?', undef, 'child'), 1,
    'live graph binds generated parent id into the child insert');

# Forms-style nested contracts resolve through relationship.domain.source.
$dbh->do('CREATE TABLE selecto_perl_test_form_children (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_id integer NOT NULL REFERENCES selecto_perl_test_graph_parents(id), note text NOT NULL)');
$dbh->do('CREATE TABLE selecto_perl_test_form_grandchildren (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, form_child_id integer NOT NULL REFERENCES selecto_perl_test_form_children(id), tag text NOT NULL)');
my $grandchild_domain = {
    name   => 'Form grandchildren',
    source => {
        source_table => 'selecto_perl_test_form_grandchildren', primary_key => 'id',
        fields => ['id', 'form_child_id', 'tag'],
        columns => {
            id            => { type => 'integer' },
            form_child_id => { type => 'integer' },
            tag           => { type => 'string' },
        },
    },
    writes => { fields => { tag => { insertable => JSON::PP::true } } },
};
my $form_domain = Selecto::Domain->parse({
    schema_version => 1,
    name           => 'FormParents',
    source         => {
        source_table => 'selecto_perl_test_graph_parents',
        primary_key  => 'id',
        fields       => ['id', 'label'],
        columns      => { id => { type => 'integer' }, label => { type => 'string' } },
        associations => {},
    },
    schemas => {}, joins => {},
    writes => {
        operations => { insert => { enabled => JSON::PP::true } },
        fields     => { label  => { insertable => JSON::PP::true } },
        relationships => {
            children => {
                writable => JSON::PP::true, cardinality => 'many', ownership => 'owned',
                allowed_ops => ['insert'], parent_key => 'id', child_key => 'parent_id',
                domain => {
                    name   => 'Form children',
                    source => {
                        source_table => 'selecto_perl_test_form_children', primary_key => 'id',
                        fields => ['id', 'parent_id', 'note'],
                        columns => {
                            id => { type => 'integer' }, parent_id => { type => 'integer' },
                            note => { type => 'string' },
                        },
                    },
                    writes => {
                        fields => { note => { insertable => JSON::PP::true } },
                        relationships => {
                            tags => {
                                writable => JSON::PP::true, cardinality => 'many', ownership => 'owned',
                                allowed_ops => ['insert'], parent_key => 'id', child_key => 'form_child_id',
                                domain => $grandchild_domain,
                            },
                        },
                    },
                },
            },
        },
    },
});
my $form_engine = Selecto::Engine->new(domain => $form_domain, adapter => Selecto->adapter(postgresql => (dbh => $dbh)));
my $form_graph = Selecto::Write::Graph->new(nodes => [
    { id => 'parent', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_graph_parents',
        assignments => { label => 'form-parent' }, metadata => { returning => ['id'] },
    ) },
    { id => 'child', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_form_children',
        assignments => { note => 'nested' },
    ), bindings => [{field => 'parent_id', from => 'parent', key => 'id'}] },
    { id => 'grandchild', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_form_grandchildren',
        assignments => { tag => 'deep' },
    ), bindings => [{field => 'form_child_id', from => 'child', key => 'id'}] },
]);
my $form_result = $form_engine->execute_graph($form_graph);
is($form_result->root->values->{id}, 2, 'forms-contract graph executes through the nested domains');
is($dbh->selectrow_array('SELECT parent_id FROM selecto_perl_test_form_children WHERE note = ?', undef, 'nested'), 2,
    'forms-contract graph binds the generated parent id');
is($dbh->selectrow_array('SELECT form_child_id FROM selecto_perl_test_form_grandchildren WHERE tag = ?', undef, 'deep'),
    $form_result->nodes->{child}->values->{id},
    'grandchild binds its generated child id through the declared edge');

my $skipped = Selecto::Write::Graph->new(nodes => [
    { id => 'parent', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_graph_parents',
        assignments => { label => 'skipped-parent' }, metadata => { returning => ['id'] },
    ) },
    { id => 'child', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_form_children',
        assignments => { note => 'nested' },
    ), bindings => [{field => 'parent_id', from => 'parent', key => 'id'}] },
    { id => 'grandchild', command => Selecto::Write::Command->new(
        operation => 'insert', relation => 'selecto_perl_test_form_grandchildren',
        assignments => { tag => 'sneaky' },
    ), bindings => [{field => 'form_child_id', from => 'parent', key => 'id'}] },
]);
eval { $form_engine->execute_graph($skipped); 1 };
is($@->code, 'write_relation_mismatch', 'a grandchild bound directly from the root is rejected');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_form_grandchildren');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_form_children');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_graph_children');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_graph_parents');
$dbh->do('DROP TABLE IF EXISTS selecto_perl_test_items');
$dbh->disconnect;
done_testing;
